### ISSUE TITLE
Update ESLint to 2.x

### ISSUE THREAD

**Issue by mciastek** [jonathanKingston/eslint-config-ember#6]
Hi,

currently available version of ESLint is 2.1.0. I think your dependencies should be updated. Also `index.js` should contain rules matching to those available now in the newest version of ESLint. Now, when I'm using `eslint-config-ember` with ESLint 2.1.0 I get that in test output: 
```bash
1:1  - Rule 'no-extra-strict' was removed and replaced by: strict (no-extra-strict)
1:1  - Rule 'no-wrap-func' was removed and replaced by: no-extra-parens (no-wrap-func)
1:1  - Rule 'spaced-line-comment' was removed and replaced by: spaced-comment (spaced-line-comment)
```

I can prepare PR if you want.

Regrads

**Comment by BrianSipple** [comment]
:+1:

**Comment by jonathanKingston** [comment]
Nightmare mode has been updated along with broccoli-lint-eslint, this is the last blocking package before we can update ember-cli-eslint

**Comment by BrianSipple** [comment]
Nice. I haven't tested it yet, but looking at the options defined here, everything still seems to be compatible with eslint@2.3.0. If that's the case, a version bump in `package.json` should be all that's needed to get things flowing smoothly. Perhaps that would be the best starting point for figuring out how to take things further in issue #2?

**Comment by BrianSipple** [comment]
I guess I spoke to soon. I'm testing out local versions of both `eslint-config-ember` and `ember-cli-eslint` using `eslint` @2.3.0, and when trying to `eslint-config-ember` inside of another app, I get this error when  I run `ember serve`:

```
Error: Cannot find module 'estraverse-fb'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at monkeypatch (/Users/bsipple/Development/ember-addons/ember-cli-eslint/node_modules/babel-eslint/index.js:59:32)
```

Apparently, this is related to `eslint 2.3.0` breaking a few things in `babel-eslint` -- the parser many might be using alongside `ember-cli-eslint`: https://github.com/babel/babel-eslint/issues/267

I was able to workaround it by installing eslint 2.2.0 as a devDependency in my app that was also trying to run my local `ember-cli-eslint`, (which, as mentioned has local symlinks to an `eslint-config-ember` project using `eslint 2.3.0`.

So... long story short, the error above is likely to be seen by anyone using our latest versions alongside `babel-eslint`. My suggestion might be to document the workaround of installing `eslint 2.2.0` directly next to where [`ember-cli-eslint` currently documents `babel-eslint` usage](https://github.com/jonathanKingston/ember-cli-eslint#eslint-babel) in the first place... at least until this behavior changes.

**Comment by jonathanKingston** [comment]
@BrianSipple thanks for your work on this!
